### ISSUE TITLE
论文中水印提取部分伪代码是不是有些问题

### ISSUE THREAD

**Issue by hychaochao** [panly2003/PaperReading#1]
关于水印提取部分有几个问题想问问捏
1、p的范围是[0,b']，b’代表什么呢
2、感觉计算在color list中的token数量的这部分伪代码有些问题？
感觉应当是这样的：
![image](https://github.com/panly2003/PaperReading/assets/91264713/65b861cd-947c-4d20-9834-8d08c9004cc4)

该说不说，这篇论文错误有点点多

**Comment by panly2003** [comment]
确实错误比较多，对上面两个问题我觉得是这样：
1. 文章里b和b'使用有点混乱，个人认为正确的表述是，对于一个b' bit的信息，先把它chunk成b = b'/ log2(r)块，这样每一块对应0~r-1中的一个数；这样的话p的取值范围应该是[0, b-1]；这个issue我在笔记的最后也提到了。
2. 确实是这样，seed应该是s

**Comment by hychaochao** [comment]
get！谢谢答复~
